### ISSUE TITLE
Single-cell python bundle request

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#214]
* link to support ticket: [#2023091360000296](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=130519) + [#2023121860001271](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=142406)
* website: ...
* installation docs: ...
* toolchain: `foss-2023a` -> user prefers newer toolchain but not all packages are available in newer one
* easyblock to use: `...`
* required dependencies:

1. Ready to use:

  * [x] SciPy-bundle-2023.07-gfbf-2023a
  * [x] matplotlib-3.7.2-gfbf-2023a
  * [x] Seaborn-0.13.2-gfbf-2023a
  * [x] PyTorch-2.1.2-foss-2023a / PyTorch-2.1.2-foss-2023a-CUDA-12.1.1   
  -----

2. Need update:

  * [x] scanpy - only for 2022a  **(scanpy-1.9.1-foss-2022a.eb includes session_info which they also want)**
  * [x] * scvi-tools-0.16.4-foss-2021a.eb / scvi-tools-0.16.4-foss-2021a-CUDA-11.3.1.eb (mudata, scvi-tools)
  * [x] * scArches-0.5.6-foss-2021a.eb / CUDA-11.3.1.eb (muon, sklearn, scArches)
  * [x] scib-metrics-0.3.3-foss-2021a.eb
  * [x] scVelo-0.2.3-foss-2021a.eb
  * [x] CellTypist-1.0.0-foss-2021b.eb 
  * [x] loompy-3.0.7-foss-2022a.eb
  * [x] epiScanpy-0.4.0-foss-2022a.eb
  * [x] CellRank-1.4.0-foss-2021a.eb **They want newer version at least v2**
  * [x] scCODA-0.1.9-foss-2021a.eb
  * [x] rpy2-3.4.5-foss-2021b.eb
  * [x] infercnvpy-0.4.2-foss-2022a.eb
  * [x] pySCENIC-0.12.1-foss-2022a.eb
  * [x] Squidpy-1.2.2-foss-2021b.eb
  -----

3. Need create:

  * [x] Anndata2ri **https://pypi.org/project/anndata2ri/**
  * [x] Bbknn **https://pypi.org/project/bbknn/**
  * [x] Cassiopeia lineage **https://pypi.org/project/cassiopeia-lineage/**
  * [x] Sc_toolbox  **https://pypi.org/project/sc-toolbox/**
  * [x] Altair **https://pypi.org/project/altair/**
  * [x] Pertpy **https://pypi.org/project/pertpy/**
  * [x] Tasccoda **https://pypi.org/project/tascCODA/**
  * [x] Liana-py **https://pypi.org/project/liana/ !There is already an easyconfig for the Liana which is a R-package - not the same**
  * [x] Harmonypy **https://pypi.org/project/harmonypy/**
  * [x] Scirpy **https://pypi.org/project/scirpy/**
  * [x] CellPhoneDB **https://pypi.org/project/CellphoneDB/**
  * [x] Decoupler **https://pypi.org/project/decoupler/**
  * [x] contrastiveVI **https://github.com/suinleelab/contrastiveVI**
    * should be part of scvi-tools now
    * https://github.com/suinleelab/contrastiveVI/tree/main?tab=readme-ov-file#user-guide
  * [x] Schist **https://github.com/dawe/schist**
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19963

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19981

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19994

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20002

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20116

**Comment by laraPPr** [comment]
They have opened a bunch of new tickets for stuff that is in the list but not yet in the bundle. Maybe it can be used as a guide for which part to look at next:

**ASAP** 
- [x] [#2024051360000881](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156207) scvi-tools + mudata + scArches + scib-metrics

**medium**
- [x] [#2024051360000916](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156210) Muon
- [x] [#2024051360000925](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156211) harmonypy (listed as extension in Single-cell bundle)
- [x] [#2024051360000934](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156212) CellPhoneDB (listed as extension in Single-cell bundle)
- [x] [#2024051360000943](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156213) Decoupler-py (listed as extension in Single-cell bundle)
- [x] [#2024051360000952](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156214) Liana (listed as extension in Single-cell bundle)
- [x] [#2024051360000961](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156215;ArticleID=550554) MuData (listed as extension in Single-cell bundle)
- [x] [#2024051360000971](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156216) Scirpy (listed as extension in Single-cell bundle)
- [x] [#2024051360001004](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156219) Pertpy
- [x] [#2024051360001013](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156220) Schist

**Comment by pavelToman** [comment]
scvi-tools + scArches + scib-metrics + Pertpy + contrastiveVI are stoped and waiting for `jax`: 
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20119

Edit: `jax` without CUDA created from PR [#20119](https://github.com/easybuilders/easybuild-easyconfigs/pull/20119)

**Comment by boegel** [comment]
Finally merged:

* https://github.com/easybuilders/easybuild-easyconfigs/pull/20116

Thanks a lot for all the effort on this @pavelToman and @PetrKralCZ!
